### ISSUE TITLE
List events (failure, success etc)

### ISSUE THREAD

**Issue by diegopasten** [GlennRicaud/data-toolbox-app#1]
Enonic XP: 6.15.8 (probably also 7.x)
Data Toolbox: 2.2.3

Bug description: 

More of a feature request. When doing dumps the tool only shows status updates in really short notifications that popup and then disappear forever. It's a bit hard to know if something completed or failed (or why it failed) unless I'm constantly monitoring. 

A list of completed/failed events or even a list of currently running tasks would help a lot.

**Comment by GlennRicaud** [comment]
Dump/Load/Export/Import are supposed to generate a report that remains displayed until closed.
If not something went wrong.

####### LOGS
In case of errors, I try to log the errors
  - In the browser console
  - In the server logs.
Now I noticed that some cases were not logged properly. This will be fixed in version 4.0.1 (>= XP 7.0.0) to be released this week-end.
I will also log in the browser the successful actions.

####### TASKS
Good idea for the tasks. It is something that was in the backlog but definitely. Will do that for 4.0.2
=> Keeping this issue open until then.

**Comment by GlennRicaud** [comment]
Tasks implemented in https://github.com/GlennRicaud/data-toolbox-app/issues/7
And released with 4.0.3
