### ISSUE TITLE
Using Data Toolbox to query for use of certain part config values

### ISSUE THREAD

**Issue by Bellfalasch** [GlennRicaud/data-toolbox-app#32]
Help Glenn! =)

So I'm interesting in querying our large dataset for existing of some outdated data. The thing is we change the data structure from time to time and that means the old data is still stored in XP but not possible to extract from within Content Studio's forms. But how do we query for component data in the Data Toolbox (or 

One example is I have a Part called `teaser` that can be placed to any page, this will add the following search path to the content - page.regions.main.components[] with an object within. But how do I write a query to find all uses of a particular part, like one called 'teaser'. I would imagine the start is this:

`page.regions.main.components.descriptor LIKE '*:teasers'`

but since components is an array and not flat I get no matches. Changing to this doesn't work:

`page.regions.main.components[].descriptor LIKE '*:teasers'`

Also, finding all uses of one particular part is great, but would also need to expand that query to check for particular configs (that we are looking into removing if they are not used, but must make sure first).

`page.regions.main.components.config.reverseSize LIKE '*'`

**Comment by GlennRicaud** [comment]
I will suppose that we are talking about XP 7.0 or superior:

One thing very confusing is that the representation of components at content level and node level is different since 7.0.
That is creating a lot of confusion.

From ContentViewer or the content-lib, it is true that the parts are represented in this tree view:
page.regions.main.components.**

<img width="418" alt="Screen Shot 2020-11-15 at 13 36 05" src="https://user-images.githubusercontent.com/12030113/99185207-aee05c80-2748-11eb-9149-237c4fe51457.png">

But in reality at the node the structure has changed since 7.0 and they are all in the same array "components" (Screenshot 2)

<img width="793" alt="Screen Shot 2020-11-15 at 13 40 48" src="https://user-images.githubusercontent.com/12030113/99185211-b6076a80-2748-11eb-94d3-818aaf4f9477.png">

You can actually see what is index / how you can search by clicking on the button:

<img width="544" alt="Screen Shot 2020-11-15 at 13 42 00" src="https://user-images.githubusercontent.com/12030113/99185217-bd2e7880-2748-11eb-8259-c8615a08bff2.png">

And see there how it is actually indexed:

<img width="437" alt="Screen Shot 2020-11-15 at 13 42 26" src="https://user-images.githubusercontent.com/12030113/99185232-c881a400-2748-11eb-90e9-b7c47bc4937f.png">

So in DT, to search for content with a component with a specific descriptor it would be the following query:

<img width="1115" alt="Screen Shot 2020-11-15 at 13 42 42" src="https://user-images.githubusercontent.com/12030113/99185240-d33c3900-2748-11eb-9e6e-8deb2638c0bb.png">

**Comment by Bellfalasch** [comment]
Oh my G.. you are such a genious! Thanks so much for the elaborate response, I can totally see how it works now and still understand how Content Viewer tricked me. I should have used the Toolbox to explore instead!
