### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')

### ISSUE THREAD

**Issue by jas7457** [GlennRicaud/data-toolbox-app#61]
I hope this is the right repository to file this, but after upgrading Data Toolbox to 5.0.18 we get an error in the data-toolbox.js file and the page fails to load because of the thrown error.

I've briefly looked at the code and can't find anywhere that "eventManager" gets defined, at least in that file.

![image](https://user-images.githubusercontent.com/1019769/142657848-a60db4df-626c-4b94-a14d-9f42d5505a3e.png)

**Comment by GlennRicaud** [comment]
Thank you for reporting this issue.

This is linked to the 2 error messages displayed in the console: the admin event websocket used by different admin tools including Content Studio or DataToolbox is not available.
One odd thing is its URL which should be by default `ws://localhost:8080/admin/event`, but is here `ws://localhost/event` (Some issue with the virtual host config? A proxy server not forwarding websocket?)

That being said, DataToolbox should handle this error (especially since the websocket is not necessary to most features).
I will work on it this weekend and you should have a new version available by the end of it.

While working on this, if you are in a blocking situation, I recommend:
- Fixing the situation with the websocket. As this might have impact on other tools like the refresh in ContentStudio 
- OR downgrading DataToolbox (version 5.0.6 should not have this issue)

**Comment by GlennRicaud** [comment]
Fixed in DataToolbox v5.0.19. This version should be available on the Enonic market on monday.
If you need it before that, you can already download it using the following URL: https://rcdsystems.jfrog.io/artifactory/maven-public/systems/rcd/enonic/datatoolbox/5.0.19/datatoolbox-5.0.19.jar

Again this will not fix your situation concerning websockets.
A guess: a proxy server not forwarding `ws://` requests
